# What is linking?
# docker build -t project_name .
# docker run -p 8080:1337 -it --rm --name project_name project_name

nginx:
  build: ./nginx
  ports:
    - "80:80"
app:
  build: ./node
  ports:
    - "8080"